### PR TITLE
Use strict

### LINKED ISSUE #2: Not working in node 4 because of `let`
This module is not working in node 4.

I get the following error when calling `require('jasmine-vow')`:

`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`.

<details><summary>See stack trace</summary><p>

    /path/to/repo/node_modules/jasmine-vow/lib/wrap.js:9
        let cb = isFunction(description)
        ^^^
    
    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/path/to/repo/node_modules/jasmine-vow/lib/vow.js:1:76)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
</p></details>

### PR DESCRIPTION
**Pull request by MiniGod**
Fixes #2, except that the dev script doesn't work.

### CODE REVIEW

**Comment by agirorn** [comment]
Why does the dev script not work?

**Comment by MiniGod** [comment]
[`yardman`](https://github.com/agirorn/yardman) is using the spread operator which is not available in node 4 except behind the --harmony flag.

**Comment by agirorn** [comment]
Thanks for the pull request.

**Comment by agirorn** [comment]
@MiniGod this has been released in v0.0.2

**Pull request merged**
